# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Construct a copula using uniform sampling from the unit simplex
#'
#' Given two families of parallel hyperplanes intersecting the canonical simplex, this function uniformly samples from the canonical simplex and construct an approximation of the bivariate probability distribution, called copula.
#'
#' @param h1 A \eqn{d}-dimensional vector that describes the direction of the first family of parallel hyperplanes.
#' @param h2 A \eqn{d}-dimensional vector that describes the direction of the second family of parallel hyperplanes.
#' @param numSlices The number of the slices for the copula. Default value is 100.
#' @param N The number of points to sample. Default value is \eqn{4\cdot 10^6}.
#'
#' @references \cite{L. Cales, A. Chalkis, I.Z. Emiris, V. Fisikopoulos,
#' \dQuote{Practical volume computation of structured convex bodies, and an application to modeling portfolio dependencies and financial crises,} \emph{Proc. of Symposium on Computational Geometry, Budapest, Hungary,} 2018.}
#'
#' @return A \eqn{numSlices\times numSlices} numerical matrix that corresponds to a copula.
#' @examples
#' # compute a copula for two random families of parallel hyperplanes
#' h1 = runif(n = 10, min = 1, max = 1000)
#' h1 = h1 / 1000
#' h2=runif(n = 10, min = 1, max = 1000)
#' h2 = h2 / 1000
#' cop = copula1(h1=h1, h2=h2, numSlices = 10, N = 100000)
#' @export
copula1 <- function(h1, h2, numSlices, N) {
    .Call(`_volesti_copula1`, h1, h2, numSlices, N)
}

#' Construct a copula using uniform sampling from the unit simplex
#'
#' Given a family of parallel hyperplanes and a family of concentric ellispoids centered at the origin intersecting the canonical simplex, this function uniformly samples from the canonical simplex and construct an approximation of the bivariate probability distribution, called copula.
#'
#' @param h A \eqn{d}-dimensional vector that describes the direction of the first family of parallel hyperplanes.
#' @param E The \eqn{d\times d} symmetric positive semidefine matrix that describes the family of concentric ellipsoids centered at the origin.
#' @param numSlices The number of the slices for the copula. Default value is 100.
#' @param N The number of points to sample. Default value is \eqn{4\cdot 10^6}.
#'
#' @references \cite{L. Cales, A. Chalkis, I.Z. Emiris, V. Fisikopoulos,
#' \dQuote{Practical volume computation of structured convex bodies, and an application to modeling portfolio dependencies and financial crises,} \emph{Proc. of Symposium on Computational Geometry, Budapest, Hungary,} 2018.}
#'
#' @return A \eqn{numSlices\times numSlices} numerical matrix that corresponds to a copula.
#' @examples
#' # compute a copula for a family of parallel hyperplanes and a family of conentric ellipsoids
#' h = runif(n = 10, min = 1, max = 1000)
#' h = h / 1000
#' E = replicate(10, rnorm(20))
#' E = cov(E)
#' cop = copula2(h=h, E=E, numSlices=10, N=100000)
#' @export
copula2 <- function(h, E, numSlices, N) {
    .Call(`_volesti_copula2`, h, E, numSlices, N)
}

get_copulas <- function(RetMat, EllMats, Win = NULL, M = NULL, N = NULL, error = NULL, prob = NULL, hnr = NULL) {
    .Call(`_volesti_get_copulas`, RetMat, EllMats, Win, M, N, error, prob, hnr)
}

emd_Bmat <- function(B, A, m, fin) {
    .Call(`_volesti_emd_Bmat`, B, A, m, fin)
}

